[package]
name = "damped-springs"
version = "0.1.2"
edition = "2021"
description = "Implementation of damped springs for smooth and springy motion."
license = "MIT"

[dependencies]
num-traits = "0.2.19"
